### ISSUE TITLE
Would be nice to have vertex buffer regions for large rooms

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/Stickers#1]
Wouldn't want to submit a single vbuff for a large room so some spatial segmentation would help that particular use case

**Comment by tabularelf** [comment]
Yeah I've been having that thought too. Going to have to restructure how I'm currently doing it, but I can wedge something in soon enough.

**Comment by tabularelf** [comment]
Added in regions. They're configurable in size per region (width and height), as well as segmented drawing too. No point in having lots of regions if half of them don't even end up on the screen! (`.Draw()` has been updated to include `x, y, width, height` as arguments, and all default to camera view)
