### ISSUE TITLE
Sprite data pre-fetching

### ISSUE THREAD

**Issue by JujuAdams** [tabularelf/Stickers#2]
`sprite_get_info()` is a little slow. If there's only e.g. 4 different sprites that will be added to a vertex buffer then I'd like to be able to pre-fetch that data ahead of usage to reduce the chances for hitching.

**Comment by tabularelf** [comment]
Yeah, only reason I'm mostly using it is to have a proper texture ID lookup. As `sprite_get_texture()` returns different pointers for each sprite subimage, and I'm not fond of that. The latter gives me an actual number counting upwards. This ensures that I can batch and sort sprites between different vertex buffers across the board. I have thought about just at the start of the game looping all of the sprites and adding them in *once* via `sprite_get_info()`, and extracting all of the texture IDs from there.

If there's any alternative suggestion, I'd be happy to incorporate.

**Comment by JujuAdams** [comment]
Nah, there's no native alternative (despite me asking for it a few times). Gotta cache that data!

**Comment by JujuAdams** [comment]
>  I have thought about just at the start of the game looping all of the sprites and adding them in once via `sprite_get_info()`

I do that with Cardboard and ... hmm ... it doesn't feel great tbh. I think this use case benefits from targeted prefetching of data because the number of different sprites you'll be drawing to a Sticker vertex buffer is gonna be far less than the total sprites in the game.

**Comment by tabularelf** [comment]
Yeah true... Well, the only other thing I could do is just let the user specify their own assets and parse those. Maybe asset tags? Hmm, could actually yeah.

**Comment by JujuAdams** [comment]
I guess ... the asset tag UI in the IDE needs a lot of work

**Comment by tabularelf** [comment]
Yeah, it's that or I give users a function for precaching. Which, I dunno. Would bring some compatiability for `sprite_add()` (not that I'm strictly aiming to support it for this)... *spins in chair*

The current system already tries to cache what it can in the worse case otherwise. But I do want to lessen the amount of data that I'm storing and only store what I absolutely need.

**Comment by tabularelf** [comment]
Yeah fuck it, a function for precaching wouldn't hurt.

**Comment by tabularelf** [comment]
Okay we have `StickersPrecacheSprite()`, and I've reimplemented how much I'm actually keeping around. I also did wedge in asset tags, but I might not keep them in the long term. Since I realized that you can't mass apply tags just via the group folder alone (loving it). 😔

**Comment by tabularelf** [comment]
Should note that `StickersPrecacheSprite()` takes in multiple arguments for sprites. Allowing `StickersPrecacheSprite(spr_blood, spr_smoke, spr_bullet_shells);`.
